[package]
name = "azure_blob"
version = "0.1.0"
authors = ["PeterReid <peter.d.reid@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "^0.9"
hmac-sha256 = "^0.1"
base64 = "^0.11"
chrono = "^0.4"
